spring.application.name=FiledataUploading
server.port=7878
# Set maximum file size (e.g., 50MB)
spring.servlet.multipart.max-file-size=50MB
# Set maximum request size (e.g., 100MB, for multiple files)
spring.servlet.multipart.max-request-size=100MB
